In [250]:
import torch
from tqdm import tqdm

In [213]:
X_train = torch.tensor([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]],dtype=torch.float32)
y_train = torch.tensor([460, 232, 178],dtype=torch.float32)

In [214]:
X_train,y_train

(tensor([[2.1040e+03, 5.0000e+00, 1.0000e+00, 4.5000e+01],
         [1.4160e+03, 3.0000e+00, 2.0000e+00, 4.0000e+01],
         [8.5200e+02, 2.0000e+00, 1.0000e+00, 3.5000e+01]]),
 tensor([460., 232., 178.]))

In [215]:
X_train.dtype

torch.float32

In [246]:
class Regression:
    def __init__(self,t_in,t_out):
        self.t_in = t_in
        self.t_out = t_out
        self.w = torch.zeros(t_in.shape[1],requires_grad=True)
        self.b = torch.tensor(0.0,requires_grad=True)

    @property
    def _loss(self):
        loss = 0.0
        for i in range(self.t_in.shape[0]):
            loss += torch.square((torch.dot(self.t_in[i],self.w) + self.b) - self.t_out[i])
        return (loss)/(2*self.t_in.shape[0])


    def train(self,epochs,l_rate):
        for i in tqdm(range(epochs),delay=0.25,total=epochs,desc="Training Process"):
            self._loss.backward()
            with torch.no_grad():
                self.w -= l_rate * self.w.grad
                self.b -= l_rate * self.b.grad
                self.w.grad.zero_()
                self.b.grad.zero_()
    
    def predict(self,test_data):
        preds = torch.zeros(test_data.shape[0])
        for i in range(test_data.shape[0]):
            preds[i] = torch.dot(test_data[i],self.w) + self.b
        return preds


In [247]:
model = Regression(X_train,y_train)

In [234]:
model.w.dtype,model.b.dtype

(torch.float32, torch.float32)

In [235]:
model.t_in.dtype

torch.float32

In [248]:
model.train(epochs=1000,l_rate =5.0e-7)

In [237]:
model.w.grad,model.b.grad

(tensor([0., 0., 0., 0.]), tensor(0.))

In [243]:
model._loss

tensor(686.7037, grad_fn=<DivBackward0>)

In [244]:
for i in range(X_train.shape[0]):
    print(f"Prediction {torch.dot(X_train[i],model.w) + model.b:0.2f} Expected {y_train[i]}")

Prediction 426.19 Expected 460.0
Prediction 286.17 Expected 232.0
Prediction 171.47 Expected 178.0


In [249]:
model.predict(X_train)

tensor([426.1853, 286.1675, 171.4677], grad_fn=<CopySlices>)